import type { Transaction } from "@/types/finance";

export const mockTransactions: Transaction[] = [
	{
		id: "1",
		title: "Website Redesign - Final Payment",
		description: "Final milestone payment from Tech Corp",
		amount: 15000,
		type: "income",
		category: "project-payment",
		status: "completed",
		date: "2025-10-01",
		projectId: "1",
		projectName: "Website Redesign",
		client: "Tech Corp",
		paymentMethod: "Bank Transfer",
		invoiceNumber: "INV-2025-001",
	},
	{
		id: "2",
		title: "Mobile App Development - Phase 1",
		description: "First phase payment",
		amount: 25000,
		type: "income",
		category: "project-payment",
		status: "completed",
		date: "2025-09-28",
		projectId: "2",
		projectName: "Mobile App Development",
		client: "Retail Solutions Inc",
		paymentMethod: "Wire Transfer",
		invoiceNumber: "INV-2025-002",
	},
	{
		id: "3",
		title: "Team Salaries - October",
		description: "Monthly payroll for all team members",
		amount: 45000,
		type: "expense",
		category: "salary",
		status: "completed",
		date: "2025-10-01",
		paymentMethod: "Payroll",
	},
	{
		id: "4",
		title: "Adobe Creative Cloud",
		description: "Annual subscription renewal",
		amount: 599,
		type: "expense",
		category: "software",
		status: "completed",
		date: "2025-10-03",
		paymentMethod: "Credit Card",
	},
	{
		id: "5",
		title: "AWS Cloud Services",
		description: "Monthly cloud infrastructure costs",
		amount: 1250,
		type: "expense",
		category: "software",
		status: "completed",
		date: "2025-10-05",
		paymentMethod: "Credit Card",
	},
	{
		id: "6",
		title: "E-commerce Platform - Deposit",
		description: "Initial deposit for new project",
		amount: 30000,
		type: "income",
		category: "project-payment",
		status: "pending",
		date: "2025-10-15",
		projectId: "4",
		projectName: "E-commerce Platform",
		client: "Fashion Outlet",
		invoiceNumber: "INV-2025-003",
	},
	{
		id: "7",
		title: "Office Rent",
		description: "Monthly office space rental",
		amount: 3500,
		type: "expense",
		category: "office",
		status: "completed",
		date: "2025-10-01",
		paymentMethod: "Bank Transfer",
	},
	{
		id: "8",
		title: "Marketing Campaign",
		description: "Q4 digital marketing budget",
		amount: 2500,
		type: "expense",
		category: "marketing",
		status: "completed",
		date: "2025-10-02",
		paymentMethod: "Credit Card",
	},
	{
		id: "9",
		title: "New MacBook Pro",
		description: "Equipment for new developer",
		amount: 3200,
		type: "expense",
		category: "equipment",
		status: "completed",
		date: "2025-09-25",
		paymentMethod: "Credit Card",
	},
	{
		id: "10",
		title: "Brand Identity - Final Payment",
		description: "Final payment for branding project",
		amount: 8500,
		type: "income",
		category: "project-payment",
		status: "completed",
		date: "2025-09-20",
		projectId: "3",
		projectName: "Brand Identity",
		client: "StartUp XYZ",
		paymentMethod: "Bank Transfer",
		invoiceNumber: "INV-2025-004",
	},
	{
		id: "11",
		title: "UX Consultant",
		description: "External UX consultant for mobile app",
		amount: 4500,
		type: "expense",
		category: "consultant",
		status: "pending",
		date: "2025-10-10",
		projectId: "2",
		projectName: "Mobile App Development",
		paymentMethod: "Bank Transfer",
	},
	{
		id: "12",
		title: "Figma Enterprise",
		description: "Design tool subscription",
		amount: 450,
		type: "expense",
		category: "software",
		status: "completed",
		date: "2025-10-04",
		paymentMethod: "Credit Card",
	},
	{
		id: "13",
		title: "Internal CRM - Milestone 1",
		description: "First milestone for internal project",
		amount: 12000,
		type: "income",
		category: "project-payment",
		status: "pending",
		date: "2025-10-20",
		projectId: "6",
		projectName: "Internal CRM System",
		invoiceNumber: "INV-2025-005",
	},
	{
		id: "14",
		title: "Conference Tickets",
		description: "Team tickets for tech conference",
		amount: 1800,
		type: "expense",
		category: "other",
		status: "completed",
		date: "2025-09-30",
		paymentMethod: "Credit Card",
	},
	{
		id: "15",
		title: "GitHub Enterprise",
		description: "Development platform subscription",
		amount: 210,
		type: "expense",
		category: "software",
		status: "completed",
		date: "2025-10-01",
		paymentMethod: "Credit Card",
	},
];
