import type { Project } from "@/types/project";

export const mockProjects: Project[] = [
	{
		id: "1",
		name: "Website Redesign",
		description: "Complete overhaul of company website with modern UI/UX",
		status: "in-progress",
		priority: "high",
		startDate: "2025-09-01",
		endDate: "2025-12-15",
		budget: {
			total: 45000,
			spent: 22500,
			remaining: 22500,
		},
		progress: 65,
		client: "Tech Corp",
		team: [
			{
				id: "1",
				name: "Sarah Johnson",
				avatar: "/images/avatars/1.png",
				role: "Designer",
			},
			{
				id: "2",
				name: "Mike Chen",
				avatar: "/images/avatars/2.png",
				role: "Developer",
			},
			{
				id: "3",
				name: "Emma Wilson",
				avatar: "/images/avatars/3.png",
				role: "PM",
			},
		],
		tags: ["web", "design", "development"],
	},
	{
		id: "2",
		name: "Mobile App Development",
		description: "iOS and Android app for customer engagement",
		status: "in-progress",
		priority: "urgent",
		startDate: "2025-08-15",
		endDate: "2026-01-30",
		budget: {
			total: 80000,
			spent: 35000,
			remaining: 45000,
		},
		progress: 45,
		client: "Retail Solutions Inc",
		team: [
			{
				id: "4",
				name: "John Doe",
				avatar: "/images/avatars/4.png",
				role: "Mobile Dev",
			},
			{
				id: "5",
				name: "Lisa Park",
				avatar: "/images/avatars/5.png",
				role: "UI Designer",
			},
		],
		tags: ["mobile", "ios", "android"],
	},
	{
		id: "3",
		name: "Brand Identity",
		description: "Create comprehensive brand guidelines and assets",
		status: "completed",
		priority: "medium",
		startDate: "2025-06-01",
		endDate: "2025-08-30",
		budget: {
			total: 25000,
			spent: 24500,
			remaining: 500,
		},
		progress: 100,
		client: "StartUp XYZ",
		team: [
			{
				id: "1",
				name: "Sarah Johnson",
				avatar: "/images/avatars/1.png",
				role: "Designer",
			},
		],
		tags: ["branding", "design"],
	},
	{
		id: "4",
		name: "E-commerce Platform",
		description: "Full-stack e-commerce solution with payment integration",
		status: "planning",
		priority: "high",
		startDate: "2026-01-15",
		budget: {
			total: 120000,
			spent: 0,
			remaining: 120000,
		},
		progress: 10,
		client: "Fashion Outlet",
		team: [
			{
				id: "2",
				name: "Mike Chen",
				avatar: "/images/avatars/2.png",
				role: "Developer",
			},
			{
				id: "6",
				name: "Alex Kumar",
				avatar: "/images/avatars/6.png",
				role: "Backend Dev",
			},
		],
		tags: ["e-commerce", "web", "backend"],
	},
	{
		id: "5",
		name: "Marketing Campaign",
		description: "Q1 2026 digital marketing campaign across all channels",
		status: "on-hold",
		priority: "low",
		startDate: "2025-11-01",
		budget: {
			total: 30000,
			spent: 5000,
			remaining: 25000,
		},
		progress: 20,
		client: "Local Business",
		team: [
			{
				id: "7",
				name: "Rachel Green",
				avatar: "/images/avatars/7.png",
				role: "Marketing",
			},
		],
		tags: ["marketing", "social-media"],
	},
	{
		id: "6",
		name: "Internal CRM System",
		description: "Custom CRM for tracking clients and projects",
		status: "in-progress",
		priority: "medium",
		startDate: "2025-09-15",
		endDate: "2025-11-30",
		budget: {
			total: 55000,
			spent: 28000,
			remaining: 27000,
		},
		progress: 55,
		team: [
			{
				id: "2",
				name: "Mike Chen",
				avatar: "/images/avatars/2.png",
				role: "Developer",
			},
			{
				id: "6",
				name: "Alex Kumar",
				avatar: "/images/avatars/6.png",
				role: "Backend Dev",
			},
			{
				id: "3",
				name: "Emma Wilson",
				avatar: "/images/avatars/3.png",
				role: "PM",
			},
		],
		tags: ["internal", "crm", "development"],
	},
];
