import type { ScheduleEvent } from "@/types/schedule";

export const mockEvents: ScheduleEvent[] = [
	{
		id: "1",
		title: "Team Standup",
		description: "Daily standup meeting with engineering team",
		type: "meeting",
		priority: "medium",
		startDate: "2025-10-06",
		startTime: "09:00",
		endTime: "09:30",
		location: "Zoom - Meeting Room 1",
		attendees: [
			{
				id: "2",
				name: "Mike Chen",
				avatar: "/images/avatars/2.png",
			},
			{
				id: "4",
				name: "John Doe",
				avatar: "/images/avatars/4.png",
			},
			{
				id: "8",
				name: "David Miller",
				avatar: "/images/avatars/8.png",
			},
		],
		color: "#3b82f6",
	},
	{
		id: "2",
		title: "Client Presentation",
		description: "Present Q4 progress to Tech Corp client",
		type: "meeting",
		priority: "high",
		startDate: "2025-10-06",
		startTime: "14:00",
		endTime: "15:30",
		location: "Conference Room A",
		projectId: "1",
		projectName: "Website Redesign",
		attendees: [
			{
				id: "1",
				name: "Sarah Johnson",
				avatar: "/images/avatars/1.png",
			},
			{
				id: "3",
				name: "Emma Wilson",
				avatar: "/images/avatars/3.png",
			},
		],
		color: "#8b5cf6",
	},
	{
		id: "3",
		title: "Website Redesign Deadline",
		description: "Final delivery date for website redesign project",
		type: "deadline",
		priority: "high",
		startDate: "2025-10-15",
		allDay: true,
		projectId: "1",
		projectName: "Website Redesign",
		color: "#ef4444",
	},
	{
		id: "4",
		title: "Design Review",
		description: "Review mobile app designs with team",
		type: "task",
		priority: "medium",
		startDate: "2025-10-07",
		startTime: "10:00",
		endTime: "11:30",
		projectId: "2",
		projectName: "Mobile App Development",
		attendees: [
			{
				id: "5",
				name: "Lisa Park",
				avatar: "/images/avatars/5.png",
			},
		],
		color: "#10b981",
		completed: false,
	},
	{
		id: "5",
		title: "Sprint Planning",
		description: "Plan sprint for next 2 weeks",
		type: "meeting",
		priority: "high",
		startDate: "2025-10-08",
		startTime: "13:00",
		endTime: "15:00",
		location: "Office - Room 3",
		attendees: [
			{
				id: "3",
				name: "Emma Wilson",
				avatar: "/images/avatars/3.png",
			},
			{
				id: "2",
				name: "Mike Chen",
				avatar: "/images/avatars/2.png",
			},
		],
		color: "#f59e0b",
	},
	{
		id: "6",
		title: "Code Review Session",
		description: "Review PRs from the week",
		type: "task",
		priority: "low",
		startDate: "2025-10-09",
		startTime: "11:00",
		endTime: "12:00",
		projectId: "6",
		projectName: "Internal CRM System",
		color: "#06b6d4",
		completed: false,
	},
	{
		id: "7",
		title: "Q4 Strategy Meeting",
		description: "Quarterly business review and planning",
		type: "meeting",
		priority: "high",
		startDate: "2025-10-10",
		startTime: "10:00",
		endTime: "12:00",
		location: "Board Room",
		attendees: [
			{
				id: "1",
				name: "Sarah Johnson",
				avatar: "/images/avatars/1.png",
			},
			{
				id: "2",
				name: "Mike Chen",
				avatar: "/images/avatars/2.png",
			},
			{
				id: "3",
				name: "Emma Wilson",
				avatar: "/images/avatars/3.png",
			},
		],
		color: "#8b5cf6",
	},
	{
		id: "8",
		title: "Team Lunch",
		description: "Monthly team building lunch",
		type: "reminder",
		priority: "low",
		startDate: "2025-10-11",
		startTime: "12:30",
		endTime: "14:00",
		location: "Italian Restaurant",
		allDay: false,
		color: "#ec4899",
	},
	{
		id: "9",
		title: "Mobile App Beta Launch",
		description: "Release beta version to test users",
		type: "milestone",
		priority: "high",
		startDate: "2025-10-20",
		allDay: true,
		projectId: "2",
		projectName: "Mobile App Development",
		color: "#f97316",
	},
	{
		id: "10",
		title: "1-on-1 with Team Leads",
		description: "Individual check-ins with team leads",
		type: "meeting",
		priority: "medium",
		startDate: "2025-10-12",
		startTime: "09:00",
		endTime: "11:00",
		location: "Office",
		color: "#3b82f6",
	},
];
