import type { TeamMember } from "@/types/team";

export const mockTeamMembers: TeamMember[] = [
	{
		id: "1",
		name: "Sarah Johnson",
		email: "sarah.johnson@upcraftcrew.com",
		avatar: "/images/avatars/1.png",
		role: "owner",
		status: "active",
		department: "Leadership",
		position: "CEO & Founder",
		joinDate: "2024-01-15",
		location: "San Francisco, CA",
		phone: "+1 (555) 123-4567",
		skills: ["Leadership", "Strategy", "Business Development"],
		projectsCount: 12,
		tasksCompleted: 145,
		performance: 98,
		bio: "Founder and CEO with 10+ years of experience in tech industry",
	},
	{
		id: "2",
		name: "Mike Chen",
		email: "mike.chen@upcraftcrew.com",
		avatar: "/images/avatars/2.png",
		role: "admin",
		status: "active",
		department: "Engineering",
		position: "CTO",
		joinDate: "2024-02-01",
		location: "Austin, TX",
		phone: "+1 (555) 234-5678",
		skills: ["Full-Stack", "Architecture", "DevOps", "React", "Node.js"],
		projectsCount: 8,
		tasksCompleted: 234,
		performance: 96,
		bio: "Tech lead passionate about scalable systems and clean code",
	},
	{
		id: "3",
		name: "Emma Wilson",
		email: "emma.wilson@upcraftcrew.com",
		avatar: "/images/avatars/3.png",
		role: "manager",
		status: "busy",
		department: "Product",
		position: "Product Manager",
		joinDate: "2024-03-10",
		location: "New York, NY",
		phone: "+1 (555) 345-6789",
		skills: ["Product Strategy", "Agile", "User Research", "Analytics"],
		projectsCount: 6,
		tasksCompleted: 189,
		performance: 94,
		bio: "Product strategist focused on user-centric solutions",
	},
	
];
