import type { TeamMember } from "@/types/team";

export const mockTeamMembers: TeamMember[] = [
	{
		id: "1",
		name: "Sarah Johnson",
		email: "sarah.johnson@upcraftcrew.com",
		avatar: "/images/avatars/1.png",
		role: "owner",
		status: "active",
		department: "Leadership",
		position: "CEO & Founder",
		joinDate: "2024-01-15",
		location: "San Francisco, CA",
		phone: "+1 (555) 123-4567",
		skills: ["Leadership", "Strategy", "Business Development"],
		projectsCount: 12,
		tasksCompleted: 145,
		performance: 98,
		bio: "Founder and CEO with 10+ years of experience in tech industry",
	},
	{
		id: "2",
		name: "Mike Chen",
		email: "mike.chen@upcraftcrew.com",
		avatar: "/images/avatars/2.png",
		role: "admin",
		status: "active",
		department: "Engineering",
		position: "CTO",
		joinDate: "2024-02-01",
		location: "Austin, TX",
		phone: "+1 (555) 234-5678",
		skills: ["Full-Stack", "Architecture", "DevOps", "React", "Node.js"],
		projectsCount: 8,
		tasksCompleted: 234,
		performance: 96,
		bio: "Tech lead passionate about scalable systems and clean code",
	},
	{
		id: "3",
		name: "Emma Wilson",
		email: "emma.wilson@upcraftcrew.com",
		avatar: "/images/avatars/3.png",
		role: "manager",
		status: "busy",
		department: "Product",
		position: "Product Manager",
		joinDate: "2024-03-10",
		location: "New York, NY",
		phone: "+1 (555) 345-6789",
		skills: ["Product Strategy", "Agile", "User Research", "Analytics"],
		projectsCount: 6,
		tasksCompleted: 189,
		performance: 94,
		bio: "Product strategist focused on user-centric solutions",
	},
	{
		id: "4",
		name: "John Doe",
		email: "john.doe@upcraftcrew.com",
		avatar: "/images/avatars/4.png",
		role: "developer",
		status: "active",
		department: "Engineering",
		position: "Senior Mobile Developer",
		joinDate: "2024-04-05",
		location: "Seattle, WA",
		phone: "+1 (555) 456-7890",
		skills: ["React Native", "iOS", "Android", "Swift", "Kotlin"],
		projectsCount: 5,
		tasksCompleted: 167,
		performance: 92,
		bio: "Mobile development specialist with focus on native performance",
	},
	{
		id: "5",
		name: "Lisa Park",
		email: "lisa.park@upcraftcrew.com",
		avatar: "/images/avatars/5.png",
		role: "designer",
		status: "active",
		department: "Design",
		position: "Lead UI/UX Designer",
		joinDate: "2024-05-12",
		location: "Los Angeles, CA",
		phone: "+1 (555) 567-8901",
		skills: ["UI Design", "UX Research", "Figma", "Prototyping", "Design Systems"],
		projectsCount: 7,
		tasksCompleted: 156,
		performance: 95,
		bio: "Creative designer crafting beautiful and intuitive experiences",
	},
	{
		id: "6",
		name: "Alex Kumar",
		email: "alex.kumar@upcraftcrew.com",
		avatar: "/images/avatars/6.png",
		role: "developer",
		status: "active",
		department: "Engineering",
		position: "Backend Developer",
		joinDate: "2024-06-20",
		location: "Remote",
		phone: "+1 (555) 678-9012",
		skills: ["Python", "Django", "PostgreSQL", "AWS", "Microservices"],
		projectsCount: 4,
		tasksCompleted: 142,
		performance: 90,
		bio: "Backend engineer specialized in scalable cloud infrastructure",
	},
	{
		id: "7",
		name: "Rachel Green",
		email: "rachel.green@upcraftcrew.com",
		avatar: "/images/avatars/7.png",
		role: "member",
		status: "away",
		department: "Marketing",
		position: "Marketing Specialist",
		joinDate: "2024-07-15",
		location: "Chicago, IL",
		phone: "+1 (555) 789-0123",
		skills: ["Digital Marketing", "SEO", "Content Strategy", "Social Media"],
		projectsCount: 3,
		tasksCompleted: 98,
		performance: 88,
		bio: "Marketing pro driving growth through data-driven campaigns",
	},
	{
		id: "8",
		name: "David Miller",
		email: "david.miller@upcraftcrew.com",
		avatar: "/images/avatars/8.png",
		role: "developer",
		status: "active",
		department: "Engineering",
		position: "Frontend Developer",
		joinDate: "2024-08-01",
		location: "Boston, MA",
		phone: "+1 (555) 890-1234",
		skills: ["React", "TypeScript", "Next.js", "TailwindCSS", "Testing"],
		projectsCount: 3,
		tasksCompleted: 87,
		performance: 89,
		bio: "Frontend enthusiast building responsive and accessible UIs",
	},
];
