packages:
  - apps/*
  - packages/*

catalog:
  '@convex-dev/better-auth': 0.9.6
  '@types/node': ^20
  better-auth: 1.3.27
  convex: ^1.27.0
  typescript: ^5

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
